[project]
name = "tf-bridge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncio>=3.4.3",
    "fastapi>=0.115.12",
    "httpx>=0.28.1",
    "jinja2>=3.1.6",
    "newrelic>=10.10.0",
    "pydantic-settings>=2.9.1",
    "uvicorn>=0.34.2",
]
